on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install cmark

      - name: Build website
        run: |
          make build/docs.html
          make
          cp build/docs.html pages/
          make site

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: docs
          folder: public
